first = input("First Name: ")
print("First name:", first)
last = input("Last Name: ")
print("Last name:", last)
middle = input("Middle Name: ")
print("Middle name:", middle)
birth = input("Birthday: ")
print("Birthday:", birth)
gender = input("Gender: ")
print("Gender:", gender)
address = input("Address: ")
print("Address:", address)
course = input("Course: ")
print("Course:", course)
year = input("Year level: ")
print("Year level:", year)

