first = input("First Name: ")
last = input("Last Name: ")
middle = input("Middle Name: ")
birth = input("Birthday: ")
gender = input("Gender: ")
address = input("Address: ")
course = input("Course: ")
year = input("Year level: ")

print("-----")
print("First name:", first)
print("Last name:", last)
print("Middle name:", middle)
print("Birthday:", birth)
print("Gender:", gender)
print("Address:", address)
print("Course:", course)
print("Year level:", year)